export const pagesRoutes = [
  ["v-0f6ce3bf","/docs/home.html",{"title":"About Me"},["/docs/home","/docs/home.md"]],
  ["v-147825fb","/docs/",{"title":"Home"},["/docs/index.html","/docs/README.md"]],
  ["v-68981c5f","/docs/guide/disable.html",{"title":"布局与功能禁用"},["/docs/guide/disable","/docs/guide/disable.md"]],
  ["v-2f223302","/docs/guide/encrypt.html",{"title":"密码加密的文章"},["/docs/guide/encrypt","/docs/guide/encrypt.md"]],
  ["v-47cf419c","/docs/guide/markdown.html",{"title":"Markdown 展示"},["/docs/guide/markdown","/docs/guide/markdown.md"]],
  ["v-a7db4e08","/docs/guide/page.html",{"title":"页面配置"},["/docs/guide/page","/docs/guide/page.md"]],
  ["v-95acbb24","/docs/guide/",{"title":"主要功能与配置演示"},["/docs/guide/index.html","/docs/guide/README.md"]],
  ["v-c12e2eca","/docs/posts/article10.html",{"title":"文章 10"},["/docs/posts/article10","/docs/posts/article10.md"]],
  ["v-bdc47d8c","/docs/posts/article11.html",{"title":"文章 11"},["/docs/posts/article11","/docs/posts/article11.md"]],
  ["v-ba5acc4e","/docs/posts/article12.html",{"title":"文章 12"},["/docs/posts/article12","/docs/posts/article12.md"]],
  ["v-6f1214c2","/docs/posts/article9.html",{"title":"文章 9"},["/docs/posts/article9","/docs/posts/article9.md"]],
  ["v-6f955c8e","/docs/articles/DeepLearning/",{"title":"深度学习"},["/docs/articles/DeepLearning/index.html","/docs/articles/DeepLearning/README.md"]],
  ["v-4d1e5d14","/docs/articles/CollegeLessons/",{"title":"学校课程"},["/docs/articles/CollegeLessons/index.html","/docs/articles/CollegeLessons/README.md"]],
  ["v-568ffdeb","/docs/articles/Development/",{"title":"开发"},["/docs/articles/Development/index.html","/docs/articles/Development/README.md"]],
  ["v-555d1562","/docs/articles/Essays/",{"title":"随笔"},["/docs/articles/Essays/index.html","/docs/articles/Essays/README.md"]],
  ["v-0899fc61","/docs/articles/MachineLearning/",{"title":"机器学习"},["/docs/articles/MachineLearning/index.html","/docs/articles/MachineLearning/README.md"]],
  ["v-d2fdb51c","/docs/articles/NaturalLanguageProcessing/",{"title":"自然语言处理"},["/docs/articles/NaturalLanguageProcessing/index.html","/docs/articles/NaturalLanguageProcessing/README.md"]],
  ["v-f39dbb64","/docs/posts/article/article1.html",{"title":"文章 1"},["/docs/posts/article/article1","/docs/posts/article/article1.md"]],
  ["v-f0340a26","/docs/posts/article/article2.html",{"title":"文章 2"},["/docs/posts/article/article2","/docs/posts/article/article2.md"]],
  ["v-ecca58e8","/docs/posts/article/article3.html",{"title":"文章 3"},["/docs/posts/article/article3","/docs/posts/article/article3.md"]],
  ["v-e960a7aa","/docs/posts/article/article4.html",{"title":"文章 4"},["/docs/posts/article/article4","/docs/posts/article/article4.md"]],
  ["v-e5f6f66c","/docs/posts/article/article5.html",{"title":"文章 5"},["/docs/posts/article/article5","/docs/posts/article/article5.md"]],
  ["v-e28d452e","/docs/posts/article/article6.html",{"title":"文章 6"},["/docs/posts/article/article6","/docs/posts/article/article6.md"]],
  ["v-df2393f0","/docs/posts/article/article7.html",{"title":"文章 7"},["/docs/posts/article/article7","/docs/posts/article/article7.md"]],
  ["v-dbb9e2b2","/docs/posts/article/article8.html",{"title":"文章 8"},["/docs/posts/article/article8","/docs/posts/article/article8.md"]],
  ["v-c5a72138","/docs/articles/DeepLearning/ReadingPapers/AlexNet.html",{"title":"AlexNet"},["/docs/articles/DeepLearning/ReadingPapers/AlexNet","/docs/articles/DeepLearning/ReadingPapers/AlexNet.md"]],
  ["v-7429dca3","/docs/articles/DeepLearning/ReadingPapers/FaceNet.html",{"title":"FaceNet"},["/docs/articles/DeepLearning/ReadingPapers/FaceNet","/docs/articles/DeepLearning/ReadingPapers/FaceNet.md"]],
  ["v-b3b9e562","/docs/articles/DeepLearning/ReadingPapers/GAN.html",{"title":"Generative Adversarial Nets"},["/docs/articles/DeepLearning/ReadingPapers/GAN","/docs/articles/DeepLearning/ReadingPapers/GAN.md"]],
  ["v-11106f12","/docs/articles/DeepLearning/ReadingPapers/ResNet.html",{"title":"ResNet"},["/docs/articles/DeepLearning/ReadingPapers/ResNet","/docs/articles/DeepLearning/ReadingPapers/ResNet.md"]],
  ["v-47a74c10","/docs/articles/DeepLearning/ReadingPapers/SENet.html",{"title":"SENet"},["/docs/articles/DeepLearning/ReadingPapers/SENet","/docs/articles/DeepLearning/ReadingPapers/SENet.md"]],
  ["v-67e9efad","/docs/articles/DeepLearning/Theories/GRU.html",{"title":"GRU"},["/docs/articles/DeepLearning/Theories/GRU","/docs/articles/DeepLearning/Theories/GRU.md"]],
  ["v-41569e0a","/docs/articles/DeepLearning/Theories/LSTM.html",{"title":"LSTM"},["/docs/articles/DeepLearning/Theories/LSTM","/docs/articles/DeepLearning/Theories/LSTM.md"]],
  ["v-01e7f836","/docs/articles/DeepLearning/Theories/RNN.html",{"title":"RNN"},["/docs/articles/DeepLearning/Theories/RNN","/docs/articles/DeepLearning/Theories/RNN.md"]],
  ["v-588b5652","/docs/articles/CollegeLessons/CompileSystem/compileLesson1.html",{"title":"语法分析"},["/docs/articles/CollegeLessons/CompileSystem/compileLesson1","/docs/articles/CollegeLessons/CompileSystem/compileLesson1.md"]],
  ["v-5a402ef1","/docs/articles/CollegeLessons/CompileSystem/compileLesson2.html",{"title":"语法制导翻译"},["/docs/articles/CollegeLessons/CompileSystem/compileLesson2","/docs/articles/CollegeLessons/CompileSystem/compileLesson2.md"]],
  ["v-5bf50790","/docs/articles/CollegeLessons/CompileSystem/compileLesson3.html",{"title":"语法制导翻译方案"},["/docs/articles/CollegeLessons/CompileSystem/compileLesson3","/docs/articles/CollegeLessons/CompileSystem/compileLesson3.md"]],
  ["v-5da9e02f","/docs/articles/CollegeLessons/CompileSystem/compileLesson4.html",{"title":"中间代码生成"},["/docs/articles/CollegeLessons/CompileSystem/compileLesson4","/docs/articles/CollegeLessons/CompileSystem/compileLesson4.md"]],
  ["v-77c48138","/docs/articles/CollegeLessons/CSAPP/finalProject.html",{"title":"程序人生-Hello's p2p"},["/docs/articles/CollegeLessons/CSAPP/finalProject","/docs/articles/CollegeLessons/CSAPP/finalProject.md"]],
  ["v-490d59fa","/docs/articles/CollegeLessons/SoftwareConstructure/lesson1.html",{"title":"静态检查"},["/docs/articles/CollegeLessons/SoftwareConstructure/lesson1","/docs/articles/CollegeLessons/SoftwareConstructure/lesson1.md"]],
  ["v-45a3a8bc","/docs/articles/CollegeLessons/SoftwareConstructure/lesson2.html",{"title":"java基础"},["/docs/articles/CollegeLessons/SoftwareConstructure/lesson2","/docs/articles/CollegeLessons/SoftwareConstructure/lesson2.md"]],
  ["v-4239f77e","/docs/articles/CollegeLessons/SoftwareConstructure/lesson3.html",{"title":"测试"},["/docs/articles/CollegeLessons/SoftwareConstructure/lesson3","/docs/articles/CollegeLessons/SoftwareConstructure/lesson3.md"]],
  ["v-3ed04640","/docs/articles/CollegeLessons/SoftwareConstructure/lesson4.html",{"title":"代码评审"},["/docs/articles/CollegeLessons/SoftwareConstructure/lesson4","/docs/articles/CollegeLessons/SoftwareConstructure/lesson4.md"]],
  ["v-3b669502","/docs/articles/CollegeLessons/SoftwareConstructure/lesson5.html",{"title":"规格说明"},["/docs/articles/CollegeLessons/SoftwareConstructure/lesson5","/docs/articles/CollegeLessons/SoftwareConstructure/lesson5.md"]],
  ["v-37fce3c4","/docs/articles/CollegeLessons/SoftwareConstructure/lesson6.html",{"title":"抽象数据类型"},["/docs/articles/CollegeLessons/SoftwareConstructure/lesson6","/docs/articles/CollegeLessons/SoftwareConstructure/lesson6.md"]],
  ["v-34933286","/docs/articles/CollegeLessons/SoftwareConstructure/lesson7.html",{"title":"抽象函数与表示不变量"},["/docs/articles/CollegeLessons/SoftwareConstructure/lesson7","/docs/articles/CollegeLessons/SoftwareConstructure/lesson7.md"]],
  ["v-31298148","/docs/articles/CollegeLessons/SoftwareConstructure/lesson8.html",{"title":"接口与枚举"},["/docs/articles/CollegeLessons/SoftwareConstructure/lesson8","/docs/articles/CollegeLessons/SoftwareConstructure/lesson8.md"]],
  ["v-5750efb2","/docs/articles/Essays/2022/2022-05-21.html",{"title":"2022-05-21 2022春考试"},["/docs/articles/Essays/2022/2022-05-21","/docs/articles/Essays/2022/2022-05-21.md"]],
  ["v-2d901b54","/docs/articles/Development/Database/SQL.html",{"title":""},["/docs/articles/Development/Database/SQL","/docs/articles/Development/Database/SQL.md"]],
  ["v-8e7ad276","/docs/articles/NaturalLanguageProcessing/ReadingPapers/DoTransformersReallyPerformBadforGraphRepresentation.html",{"title":"Do Transformers Really Perform Bad for Graph Representation"},["/docs/articles/NaturalLanguageProcessing/ReadingPapers/DoTransformersReallyPerformBadforGraphRepresentation","/docs/articles/NaturalLanguageProcessing/ReadingPapers/DoTransformersReallyPerformBadforGraphRepresentation.md"]],
  ["v-6e9f0282","/docs/articles/NaturalLanguageProcessing/ReadingPapers/Hierarchy-AwareGlobalModelForHierarchicalTextClassification.html",{"title":"Hierarchy-Aware Global Model for Hierarchical Text Classification"},["/docs/articles/NaturalLanguageProcessing/ReadingPapers/Hierarchy-AwareGlobalModelForHierarchicalTextClassification","/docs/articles/NaturalLanguageProcessing/ReadingPapers/Hierarchy-AwareGlobalModelForHierarchicalTextClassification.md"]],
  ["v-0fa093f0","/docs/articles/NaturalLanguageProcessing/ReadingPapers/IncorporatingHierarchyIntoTextEncoder.html",{"title":"Incorporating Hierarchy into Text Encoder"},["/docs/articles/NaturalLanguageProcessing/ReadingPapers/IncorporatingHierarchyIntoTextEncoder","/docs/articles/NaturalLanguageProcessing/ReadingPapers/IncorporatingHierarchyIntoTextEncoder.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
  ["v-26c31203","/docs/slide.html",{"title":"幻灯片页"},["/docs/slide","/docs/slide.md"]],
]
